---
services:
  certificate.stream:
    image: certificate.stream:latest
    container_name: certificate.stream_s3_google
    environment:
      - AWS_ENDPOINT_URL=http://aws-s3:4566
      - AWS_ACCESS_KEY_ID=boo
      - AWS_SECRET_ACCESS_KEY=hoo
      - AWS_DEFAULT_REGION=us-east-1
      - SINK_S3_BUCKET_NAME=ctlogs
      - SINK_S3_BUCKET_PREFIX=logs
      - SINK_S3_USE_DATE_PARTITIONING=true
    entrypoint: >
      sh -c "sleep 25s && certificate stream -s s3 -o google -d"

  aws-s3:
    image: localstack/localstack:3.2
    container_name: aws-s3
    hostname: aws-s3
    environment:
      - DEBUG=1
      - PORT_WEB_UI=9999
      - START_WEB=1
      - SERVICES=s3,dynamodb,sts
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws/bootstrap/:/etc/localstack/init/ready.d/
      - ./aws/resources:/tmp/resources

  s3-consumer:
    build: 
      context: consumers
      dockerfile: Dockerfile
    container_name: s3-consumer
    environment:
      - BUCKET_NAME=ctlogs
      - BUCKET_PREFIX=logs
      - AWS_ENDPOINT_URL=http://aws-s3:4566
      - AWS_ACCESS_KEY_ID=boo
      - AWS_SECRET_ACCESS_KEY=hoo
      - AWS_DEFAULT_REGION=us-east-1
    command: consumer_firehose_s3.py
